import type { Metadata } from 'next';
import { Inter, Playfair_Display } from 'next/font/google';
import './globals.css';
import '../styles/chat.css';
import { ProviderWrapper, YnadexProvider } from '@/providers';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const roboto_mono = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
});

interface IProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'ConsultInfo',
  description: 'Generated by create next app',
};

const Application = ({ children }: IProps) => children;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto_mono.variable} scroll-smooth`}>
      <body className={`${inter.className} text-[18px]`}>
        <ProviderWrapper>
          <YnadexProvider>
            <Application>{children}</Application>
          </YnadexProvider>
        </ProviderWrapper>
      </body>
    </html>
  );
}
